# Generated by Django 5.2.5 on 2025-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgitems',
            name='arq',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
