# Generated by Django 5.2.5 on 2025-09-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='preco_base',
        ),
    ]
