# Generated by Django 5.2.5 on 2025-09-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidorecebido',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrinho'),
        ),
        migrations.AlterField(
            model_name='pedidorecebido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
