# Generated by Django 5.2.5 on 2025-09-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pizza_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='CarrinhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.carrinho')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza')),
            ],
        ),
    ]
