# Generated by Django 5.2.5 on 2025-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedidorecebido_carrinho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorecebido',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
