# Generated by Django 5.2.5 on 2025-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_royal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentos',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
