# Generated by Django 5.2.5 on 2025-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_royal', '0002_investimentos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentos',
            name='descricao',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Descrição'),
        ),
    ]
